import { MenuItem } from "./types";

export const DEMO_MENU_ITEMS: MenuItem[] = [
  // ENTRÉES
  {
    id: "1",
    name_fr: "Tartare de bœuf classique",
    description_fr: "Bœuf Angus haché à la main, câpres, cornichons, jaune d'œuf, moutarde de Dijon, croûtons grillés",
    category: "entrees",
    price: 18.0,
    image_url: "https://images.unsplash.com/photo-1544025162-d76694265947?w=600&auto=format&fit=crop",
    is_vegetarian: false,
    is_gluten_free: false,
    is_popular: true,
    is_new: false,
    is_available: true,
    sort_order: 1,
    created_at: new Date().toISOString(),
  },
  {
    id: "2",
    name_fr: "Soupe à l'oignon gratinée",
    description_fr: "Bouillon de bœuf maison, oignons caramélisés, croûton de pain artisanal, fromage St-Guillaume fondu",
    category: "entrees",
    price: 14.0,
    image_url: "https://images.unsplash.com/photo-1547592166-23ac45744acd?w=600&auto=format&fit=crop",
    is_vegetarian: true,
    is_gluten_free: false,
    is_popular: true,
    is_new: false,
    is_available: true,
    sort_order: 2,
    created_at: new Date().toISOString(),
  },
  {
    id: "3",
    name_fr: "Poutine au canard confit",
    description_fr: "Frites de pommes de terre locales, fromage en grains de la Fromagerie Lambert, canard confit effiloché, sauce brune maison",
    category: "entrees",
    price: 22.0,
    image_url: "https://images.unsplash.com/photo-1630431341973-02e1b662ec35?w=600&auto=format&fit=crop",
    is_vegetarian: false,
    is_gluten_free: true,
    is_popular: false,
    is_new: true,
    is_available: true,
    sort_order: 3,
    created_at: new Date().toISOString(),
  },
  {
    id: "4",
    name_fr: "Plateau de fromages québécois",
    description_fr: "Sélection de 4 fromages artisanaux du Québec, confiture de figues, noix caramélisées, craquelins",
    category: "entrees",
    price: 24.0,
    image_url: "https://images.unsplash.com/photo-1452195100486-9cc805987862?w=600&auto=format&fit=crop",
    is_vegetarian: true,
    is_gluten_free: false,
    is_popular: false,
    is_new: false,
    is_available: true,
    sort_order: 4,
    created_at: new Date().toISOString(),
  },
  {
    id: "5",
    name_fr: "Crevettes poêlées à l'ail",
    description_fr: "Crevettes tigrées, beurre d'ail et fines herbes, citron confit, pain baguette artisanal",
    category: "entrees",
    price: 20.0,
    image_url: "https://images.unsplash.com/photo-1565680018434-b513d5e5fd47?w=600&auto=format&fit=crop",
    is_vegetarian: false,
    is_gluten_free: true,
    is_popular: false,
    is_new: false,
    is_available: true,
    sort_order: 5,
    created_at: new Date().toISOString(),
  },

  // PLATS PRINCIPAUX
  {
    id: "6",
    name_fr: "Côte de bœuf pour deux",
    description_fr: "Côte de bœuf Angus 800g, beurre maître d'hôtel, pommes de terre grenailles rôties, légumes du marché",
    category: "plats",
    price: 89.0,
    image_url: "https://images.unsplash.com/photo-1558030006-450675393462?w=600&auto=format&fit=crop",
    is_vegetarian: false,
    is_gluten_free: true,
    is_popular: true,
    is_new: false,
    is_available: true,
    sort_order: 1,
    created_at: new Date().toISOString(),
  },
  {
    id: "7",
    name_fr: "Burger Le Bœuf & Bière",
    description_fr: "Galette bœuf Angus 200g, bacon croustillant, cheddar vieilli, oignons caramélisés à la bière blonde, frites maison",
    category: "plats",
    price: 26.0,
    image_url: "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=600&auto=format&fit=crop",
    is_vegetarian: false,
    is_gluten_free: false,
    is_popular: true,
    is_new: false,
    is_available: true,
    sort_order: 2,
    created_at: new Date().toISOString(),
  },
  {
    id: "8",
    name_fr: "Saumon de l'Atlantique",
    description_fr: "Filet de saumon poêlé, purée de céleri-rave, beurre blanc au citron, asperges vertes, câpres",
    category: "plats",
    price: 34.0,
    image_url: "https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?w=600&auto=format&fit=crop",
    is_vegetarian: false,
    is_gluten_free: true,
    is_popular: false,
    is_new: true,
    is_available: true,
    sort_order: 3,
    created_at: new Date().toISOString(),
  },
  {
    id: "9",
    name_fr: "Risotto aux champignons sauvages",
    description_fr: "Champignons forestiers du Québec, parmesan vieilli 24 mois, truffe noire, huile d'olive extra-vierge",
    category: "plats",
    price: 28.0,
    image_url: "https://images.unsplash.com/photo-1476124369491-e7addf5db371?w=600&auto=format&fit=crop",
    is_vegetarian: true,
    is_gluten_free: true,
    is_popular: false,
    is_new: false,
    is_available: true,
    sort_order: 4,
    created_at: new Date().toISOString(),
  },
  {
    id: "10",
    name_fr: "Poulet rôti aux herbes",
    description_fr: "Poulet fermier entier rôti, sauce au jus, pommes de terre dauphinoises, salade verte",
    category: "plats",
    price: 32.0,
    image_url: "https://images.unsplash.com/photo-1598103442097-8b74394b95c8?w=600&auto=format&fit=crop",
    is_vegetarian: false,
    is_gluten_free: true,
    is_popular: false,
    is_new: false,
    is_available: true,
    sort_order: 5,
    created_at: new Date().toISOString(),
  },
  {
    id: "11",
    name_fr: "Pâtes à la carbonara maison",
    description_fr: "Linguines fraîches, pancetta croustillante, pecorino romano, œufs biologiques, poivre noir concassé",
    category: "plats",
    price: 24.0,
    image_url: "https://images.unsplash.com/photo-1612874742237-6526221588e3?w=600&auto=format&fit=crop",
    is_vegetarian: false,
    is_gluten_free: false,
    is_popular: false,
    is_new: false,
    is_available: true,
    sort_order: 6,
    created_at: new Date().toISOString(),
  },

  // GRILLADES
  {
    id: "12",
    name_fr: "Entrecôte 300g",
    description_fr: "Entrecôte Angus élevé au grain, cuisson au charbon de bois, sauce au poivre vert, frites maison",
    category: "grillades",
    price: 42.0,
    image_url: "https://images.unsplash.com/photo-1600891964092-4316c288032e?w=600&auto=format&fit=crop",
    is_vegetarian: false,
    is_gluten_free: true,
    is_popular: true,
    is_new: false,
    is_available: true,
    sort_order: 1,
    created_at: new Date().toISOString(),
  },
  {
    id: "13",
    name_fr: "Filet mignon 250g",
    description_fr: "Filet de bœuf tendre, sauce au foie gras, purée de pommes de terre truffée, haricots verts",
    category: "grillades",
    price: 52.0,
    image_url: "https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=600&auto=format&fit=crop",
    is_vegetarian: false,
    is_gluten_free: true,
    is_popular: false,
    is_new: false,
    is_available: true,
    sort_order: 2,
    created_at: new Date().toISOString(),
  },
  {
    id: "14",
    name_fr: "Côtelettes d'agneau",
    description_fr: "Rack d'agneau du Québec, herbes de Provence, tapenade d'olives, ratatouille provençale",
    category: "grillades",
    price: 46.0,
    image_url: "https://images.unsplash.com/photo-1529694157872-4e0c0f3b238b?w=600&auto=format&fit=crop",
    is_vegetarian: false,
    is_gluten_free: true,
    is_popular: false,
    is_new: true,
    is_available: true,
    sort_order: 3,
    created_at: new Date().toISOString(),
  },

  // BIÈRES MAISON
  {
    id: "15",
    name_fr: "La Forge — Blonde artisanale",
    description_fr: "Bière blonde légère et rafraîchissante, notes de miel et de céréales. 5.2% alc.",
    category: "bieres",
    price: 8.5,
    image_url: "https://images.unsplash.com/photo-1608270586620-248524c67de9?w=600&auto=format&fit=crop",
    is_vegetarian: true,
    is_gluten_free: false,
    is_popular: true,
    is_new: false,
    is_available: true,
    sort_order: 1,
    created_at: new Date().toISOString(),
  },
  {
    id: "16",
    name_fr: "La Mauricie — IPA houblonnée",
    description_fr: "India Pale Ale généreusement houblonnée, arômes d'agrumes et de résine. 6.5% alc.",
    category: "bieres",
    price: 9.0,
    image_url: "https://images.unsplash.com/photo-1532634922-8fe0b757fb13?w=600&auto=format&fit=crop",
    is_vegetarian: true,
    is_gluten_free: false,
    is_popular: true,
    is_new: false,
    is_available: true,
    sort_order: 2,
    created_at: new Date().toISOString(),
  },
  {
    id: "17",
    name_fr: "La Noire de Trois-Rivières",
    description_fr: "Stout impérial aux notes de café torréfié et de chocolat noir. 7.8% alc.",
    category: "bieres",
    price: 9.5,
    image_url: "https://images.unsplash.com/photo-1559526324-4b87b5e36e44?w=600&auto=format&fit=crop",
    is_vegetarian: true,
    is_gluten_free: false,
    is_popular: false,
    is_new: false,
    is_available: true,
    sort_order: 3,
    created_at: new Date().toISOString(),
  },
  {
    id: "18",
    name_fr: "La Brasseur — Rousse fumée",
    description_fr: "Bière rousse aux malts fumés, caractère robuste, finale longue et chaleureuse. 5.8% alc.",
    category: "bieres",
    price: 9.0,
    image_url: "https://images.unsplash.com/photo-1436076863939-06870fe779c2?w=600&auto=format&fit=crop",
    is_vegetarian: true,
    is_gluten_free: false,
    is_popular: false,
    is_new: true,
    is_available: true,
    sort_order: 4,
    created_at: new Date().toISOString(),
  },
  {
    id: "19",
    name_fr: "La Belle Saison",
    description_fr: "Saison belge aux épices, notes d'orange et de coriandre, pétillante et estivale. 6.2% alc.",
    category: "bieres",
    price: 9.0,
    image_url: "https://images.unsplash.com/photo-1571091718767-18b5b1457add?w=600&auto=format&fit=crop",
    is_vegetarian: true,
    is_gluten_free: false,
    is_popular: false,
    is_new: false,
    is_available: true,
    sort_order: 5,
    created_at: new Date().toISOString(),
  },
  {
    id: "20",
    name_fr: "Bière du moment — Spéciale saisonnière",
    description_fr: "Notre création éphémère du brasseur — demandez au serveur pour les détails. Quantités limitées.",
    category: "bieres",
    price: 10.0,
    image_url: "https://images.unsplash.com/photo-1566843972142-a7fcb70de55b?w=600&auto=format&fit=crop",
    is_vegetarian: true,
    is_gluten_free: false,
    is_popular: false,
    is_new: true,
    is_available: true,
    sort_order: 6,
    created_at: new Date().toISOString(),
  },

  // DESSERTS
  {
    id: "21",
    name_fr: "Fondant au chocolat noir",
    description_fr: "Cœur coulant de chocolat 70%, glace à la vanille de Tahiti, coulis de framboises",
    category: "desserts",
    price: 12.0,
    image_url: "https://images.unsplash.com/photo-1624353365286-3f8d62daad51?w=600&auto=format&fit=crop",
    is_vegetarian: true,
    is_gluten_free: false,
    is_popular: true,
    is_new: false,
    is_available: true,
    sort_order: 1,
    created_at: new Date().toISOString(),
  },
  {
    id: "22",
    name_fr: "Tarte au sucre traditionnelle",
    description_fr: "Recette grand-mère, sirop d'érable du Québec, crème fouettée à la fleur de sel",
    category: "desserts",
    price: 10.0,
    image_url: "https://images.unsplash.com/photo-1464305795204-6f5bbfc7fb81?w=600&auto=format&fit=crop",
    is_vegetarian: true,
    is_gluten_free: false,
    is_popular: true,
    is_new: false,
    is_available: true,
    sort_order: 2,
    created_at: new Date().toISOString(),
  },
  {
    id: "23",
    name_fr: "Crème brûlée à l'érable",
    description_fr: "Crème onctueuse parfumée au sirop d'érable, caramel craquant, sucre à la cassonade",
    category: "desserts",
    price: 11.0,
    image_url: "https://images.unsplash.com/photo-1470124182917-cc6e71b22ecc?w=600&auto=format&fit=crop",
    is_vegetarian: true,
    is_gluten_free: true,
    is_popular: false,
    is_new: false,
    is_available: true,
    sort_order: 3,
    created_at: new Date().toISOString(),
  },
  {
    id: "24",
    name_fr: "Gâteau au fromage et coulis de bleuets",
    description_fr: "Fromage à la crème onctueux sur croûte sablée, coulis de bleuets sauvages du Lac-Saint-Jean",
    category: "desserts",
    price: 11.0,
    image_url: "https://images.unsplash.com/photo-1533134242443-d4fd215305ad?w=600&auto=format&fit=crop",
    is_vegetarian: true,
    is_gluten_free: false,
    is_popular: false,
    is_new: true,
    is_available: true,
    sort_order: 4,
    created_at: new Date().toISOString(),
  },

  // BOISSONS
  {
    id: "25",
    name_fr: "Limonade maison à l'érable",
    description_fr: "Citrons pressés, sirop d'érable, eau pétillante, menthe fraîche",
    category: "boissons",
    price: 6.0,
    image_url: "https://images.unsplash.com/photo-1621263764928-df1444c5e859?w=600&auto=format&fit=crop",
    is_vegetarian: true,
    is_gluten_free: true,
    is_popular: false,
    is_new: false,
    is_available: true,
    sort_order: 1,
    created_at: new Date().toISOString(),
  },
  {
    id: "26",
    name_fr: "Café de spécialité",
    description_fr: "Espresso simple ou double, torréfaction locale, option lait d'avoine ou noisette",
    category: "boissons",
    price: 4.5,
    image_url: "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=600&auto=format&fit=crop",
    is_vegetarian: true,
    is_gluten_free: true,
    is_popular: false,
    is_new: false,
    is_available: true,
    sort_order: 2,
    created_at: new Date().toISOString(),
  },
  {
    id: "27",
    name_fr: "Cocktail sans alcool — Pomme & Gingembre",
    description_fr: "Jus de pomme de verger local, gingembre frais, citron vert, eau tonique, glaçons",
    category: "boissons",
    price: 7.0,
    image_url: "https://images.unsplash.com/photo-1544145945-f90425340c7e?w=600&auto=format&fit=crop",
    is_vegetarian: true,
    is_gluten_free: true,
    is_popular: false,
    is_new: true,
    is_available: true,
    sort_order: 3,
    created_at: new Date().toISOString(),
  },
  {
    id: "28",
    name_fr: "Sélection de vins au verre",
    description_fr: "Demandez à notre sommelier — sélection de vins biologiques du Québec et d'importation privée",
    category: "boissons",
    price: 12.0,
    image_url: "https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?w=600&auto=format&fit=crop",
    is_vegetarian: true,
    is_gluten_free: true,
    is_popular: false,
    is_new: false,
    is_available: true,
    sort_order: 4,
    created_at: new Date().toISOString(),
  },
];
